### ISSUE TITLE
Documentation systems

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create-Prepare-to-Dye#113]
The systems responsible for helping the player navigate the mechanics and elements of the pack.

**Goals**
- never needing to check outside the game for a mechanic or item or anything else related to the game
> example: access to villiger breeding mechanics
- the player wants to do a specific thing they can search jei using general terms to find what tools, blocks and mechanics are related. Everything is cataloged
- the player should be able to learn about those documentation systems without intrusive tutorials

**Comment by PandaBoy444** [comment]
Translatable
