### ISSUE TITLE
Discord bot

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create-Prepare-to-Dye#127]
Where / is command prefix whatever that might be in the future
Should be able to :
- create issues
> - any channel
```
basic sytax
/issue text ##tag
autotag
/todo/task/mission/ (doesn't actually tag, just a shortcut to regular issue adding) 
/bug/peoblem/report/ ##bug
/suggest /suggestion /idea /thought
/document /documentation /tooltip
```
- close issues
```
/close /done /finish /complete /obliterate /kill [id] [text] 
Also reacting with any checkmark or x emoji should close issues 
```
- reopen issues
```
/open /reopen /welcomeback /resurrect [id] [text] 
```
- comment on issues
```
/[id] 
```

- add tooltips

**Comment by PandaBoy444** [comment]
Reflect Readme (and potentially other files)
```
/add reflect readme.md
```

**Comment by PandaBoy444** [comment]
When opening a new thread, bot will ask "should this be a github issue?" and if people react with any checkmark or /yes it turns into an issue thread

**Comment by PandaBoy444** [comment]
When an issue gets created it also opens a thread and everything written in the thread goes to syncs to github (maybe edits as well?)

**Comment by Yarden-zamir** [comment]
Not needed for now
