### ISSUE TITLE
Apply color theme to all relevent items

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create-Prepare-to-Dye#192]
Color Themed materials:

- White material - iron
- Red material - redstone
- Orange material - copper
  - Will be obtained by smelting clay
- Yellow material - brass + gold
- Blue material - manasteel + lapis
  - Related to magicstuffs
- Black material - netherite
  - Obtained by grinding obsidian - low chance of production
  - used in recipes using lava
- Green material - maybe terrasteel?
  - Obtained by oxidizing orange material
  - needs proper usages
    - idea - maybe bonemeal will be green and be obtained from green material

Retexturing needed
- [x] #213
- [ ] #214
- [ ] #215
- [x] #216

Additional notes:
- Gold block will be renamed to "Polished Yellow Metal Block" and will be made by sandpapering/etc yellow metal block (brass)

**Comment by TulkinRB** [comment]
- [ ] meow

**Comment by TulkinRB** [comment]
- [ ] meow

**Comment by Yarden-zamir** [comment]
@TulkinRB still need crushed raw iron
