### ISSUE TITLE
Water seems to spread infintetly

### ISSUE THREAD

**Issue by StuiterKoning** [Yarden-zamir/Create-Prepare-to-Dye#242]
when breaking a block next to a water source, instead of flowing over, the water creates a sourceblock in the destroyed blocks position

**Comment by Yarden-zamir** [comment]
Ah thanks for the report, sounds like something forgery would do. I'll take a look

**Comment by Yarden-zamir** [comment]
Yup, that's indeed the case, fix will be deployed in a few seconds
