### ISSUE TITLE
crashed spaceship doesnt spawn when cheats are not enabled

### ISSUE THREAD

**Issue by StuiterKoning** [Yarden-zamir/Create-Prepare-to-Dye#248]
the spaceship only spawns on world generation when cheats are enabled on world generation

**Comment by Yarden-zamir** [comment]
You sure about that? I never allow chests on worldgen and it worked for me everytime I tried

**Comment by StuiterKoning** [comment]
whenever I start a world in survival without cheats, the spaceship never generates. (cheats not bonus chest)

**Comment by TulkinRB** [comment]
Just tested it out and it doesn't generate for me as well. Did you see any command blocks near you though? I'm trying to figure out which step fails.

**Comment by Yarden-zamir** [comment]
Does something pop in the logs?

**Comment by Yarden-zamir** [comment]
Seems to be solved when I use the server loaded event instead like so
```javascript
ServerEvents.loaded((event) => {
	if(!event.server.persistentData.crashLanded)
		event.server.persistentData.crashLanded = true;
		event.server.runCommandSilent("place structure minecraft:spaceship_wreck_main");
})
```

**Comment by Yarden-zamir** [comment]
I just reread the title and saw you actually wrote cheats. I was sure you wrote chests all this time lol.
