### ISSUE TITLE
Lime

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create-Prepare-to-Dye#26]
"Today, lime is used in many areas of life: in the construction of houses and roads, in the production of glass and plastic materials and in hygiene products, as well as jewelry and food.

The chemical industry uses lime, too. For example, it is used to produce citric acid, polyvalent alcohols and synthetic plasters. It is also used as a reactant in chemical synthesis or to change the pH value. Lime is truly a versatile material."
We have limesand and limestone, I'm considering removing limestone and changing limesand into lime

**Comment by PandaBoy444** [comment]
https://www.jrank.org/api/search/v2?key=65f1cbc8eeb6f0bf1517478dfb9dd359e4dde6fa&q=lime

**Comment by Yarden-zamir** [comment]
Not needed because of our color theme #192
