### ISSUE TITLE
sell leather to player

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create-Prepare-to-Dye#329]

**Comment by EngineerSmith** [comment]
What if we rename, and retexture horse amour to scrap. Then the players can get scrap which they need to break down and, with the current recipes, this will give them leather.

**Comment by Yarden-zamir** [comment]
Not sure what you mean by scrap. But I prefer to sell hourses to players and let them do hourse farms

**Comment by Yarden-zamir** [comment]
Though i feel like people won't like killing hourses

**Comment by EngineerSmith** [comment]
No; not killing horses. But companies send/sell 'scrap' (retextured horse amour items) and the player can then grind them into useful items. The recipe is already in the game, so a texture swap would allow an extra process as you'd need a factory to break up the 'scrap' given to the player (horse amour items, not horses themselves). 

So companies given horse amour to players -> players take it and use it in a create's crushing wheels -> chance to get leather, white/yellow/orange ingots, and string (string is needed for conductor caps after all; so then you can make train timetables)

**Comment by Yarden-zamir** [comment]
Yea I know you meant hours armor, was talking about actual horses because it's more mechanically interesting to farm

**Comment by Yarden-zamir** [comment]
I like the scrap idea, but we can add it as new item, no need to reporpus horse armor

**Comment by Yarden-zamir** [comment]
In general we can have companies send you a few types of scrap for recycling, that will be cool
