### ISSUE TITLE
Delivery table can be a great inconvenience

### ISSUE THREAD

**Issue by HenceTheBeetroot** [Yarden-zamir/Create-Prepare-to-Dye#384]
As of current, the delivery table spawns in some radius around where you use the spawning item. This can be a great inconvenience if it spawns in an area difficult to get to from a set-up / Betsy; for example, if your set-up is on a high mountain and the table falls into a nearby ravine, or vice-versa.

Possible fixes:
- More control over where it spawns (for example, spawning directly where you use the item)
- Changing the table to be mineable and placeable; alternatively, if a more stationary table is desired...
- ...changing the table to be movable by Create contraptions (oddly enough, the bedrock under the table is movable, but not the table itself)
- something else idk

**Comment by Yarden-zamir** [comment]
This is very true, in the latest version he placement becomes deterministic. When you start a new world a trading platform spawns iimiditly, plus you get a tranciever to place where you like. It will spawn where you are standing when using the tranciever

**Comment by Yarden-zamir** [comment]
Try the new version and see if fixes your gripes

**Comment by HenceTheBeetroot** [comment]
wow you guys update quickly

and yeah that pretty much does it, good job!

**Comment by HenceTheBeetroot** [comment]
guess I can close this

**Comment by Yarden-zamir** [comment]
Awesome! Yes, we have a really solid codebase and we have really great people in our comunity that help test, develop, check, write documentation, and make art and assets. All of this along with great automation tools and CI helps us develop at a really good pace (I think the fastest pace a modpack has ever been developed, I'd put money on that actually) which is really fun
