### ISSUE TITLE
Multi-color random worlds

### ISSUE THREAD

**Issue by PublicVoidUpdate** [Yarden-zamir/Create-Prepare-to-Dye#390]
a system of randomly having a different colored world at like one with more warm colors, or even biomes with different colors would be really cool, and i feel the PTD experience would greatly benefit.

**Comment by PublicVoidUpdate** [comment]
this would also help people spread out more as it gives more of a reason to explore.

**Comment by Yarden-zamir** [comment]
That does sound like it would, although that is something we actually want to specifically not encorage, we want the player to not have a specific incentive or need for explration as that is not the gameplay loop we want to create

**Comment by PublicVoidUpdate** [comment]
that is very fair, however if the colors are something random and worldwide, or if there is no gameplay difference the only reason people would branch out is for aesthetics.
