### ISSUE TITLE
cant "assemble" fluid pipes

### ISSUE THREAD

**Issue by PublicVoidUpdate** [Yarden-zamir/Create-Prepare-to-Dye#393]
putting fluid pipes in the assembler menu resupts in an empty menu, this is not true for vice versa though.

**Comment by PublicVoidUpdate** [comment]
nevermind this looks planned in the menu.

**Comment by Yarden-zamir** [comment]
This is because 4 fluid pipes sre one sealed device

**Comment by PublicVoidUpdate** [comment]
nevermind this looks planned in the menu.yup 😅 i was playing an old version, then updated and got really confused why i couldn't make copper pipe. ide delete this since it isnt an issue, juse my dumbass, but im on mobile and it wont let me.
