### ISSUE TITLE
way to turn off fast night?

### ISSUE THREAD

**Issue by PublicVoidUpdate** [Yarden-zamir/Create-Prepare-to-Dye#394]
i have shaders that make the night pretty but it goes by so fast. is there a gamerule to set it to last as long as the day?

**Comment by Yarden-zamir** [comment]
Yes, we are using a mod called hourglass for that. Don't remember the exact command, you can check it out here https://github.com/DuckyCrayfish/hourglass#hourglass-config-config-key-value

**Comment by PublicVoidUpdate** [comment]
thank you! also just want to say, this is imediately one of my favorite modpacks,.

**Comment by Yarden-zamir** [comment]
That's really awesome to hear! Thanks!
