### ISSUE TITLE
Add key fluids to the #create:bottomless/allow tag

### ISSUE THREAD

**Issue by KevinSCoursey** [Yarden-zamir/Create-Prepare-to-Dye#400]
Adding the following fluids to the #create:bottomless/allow tag, which is currently set to 4000 source blocks required to be considered infinite, would provide a gateway for larger end-game farms.

Base fluids for consideration:
 - Milk
 - Honey
 - Chocolate

**Comment by Yarden-zamir** [comment]
> Thank you for the PR but I do not want them to be in the buttomless tag. Something important for this pack is that there are no "functional tiers" as much as possible. Meaning there is not supoosed to be a stage that lets you ignore a process because you have a flat upgrade. For example milk automation is such an awesomely cool thing that the players won't need after some point because they flat out made enough? I don't like. I always say, price is bedside the point, should be infrastructure that is the requirement for things, not amounts of things. Hope that makes sense. You can read the designdoc in the root folder of the pack, it's a bit outdated but has some useful concepts
#401
