### ISSUE TITLE
You can't turn secondary linear chassis back into mechanical devices

### ISSUE THREAD

**Issue by gamma-delta** [Yarden-zamir/Create-Prepare-to-Dye#437]
Adding `create:secondary_linear_chassis` to `#forge:device/andesite` would probably fix that

**Comment by jasperalani** [comment]
I've added the block @gamma-delta, if you wouldn't mind closing the ticket thanks

**Comment by Yarden-zamir** [comment]
Currently they are a quark varient. So they should not be aviliable in item form but are when you wrench them. I'm starting to hate the quark varient system very much, too many edge cases. I think soon I'll remove it and move to the personall assembler for anything that was a varient before. @jasperalani I'm not sure what you added and where

**Comment by jasperalani** [comment]
Changes are here: #441

**Comment by Yarden-zamir** [comment]
Oh I see. You should also take it out of quark varients in their config in this case. My bad for not reviewing properly. Also, did it work in game? As I tried and didn't see the recipe

**Comment by jasperalani** [comment]
Ok, yeah it worked for me

**Comment by gamma-delta** [comment]
Cool thanks!

**Comment by jasperalani** [comment]
> `secondary_linear_chassis`

When you say take it out of the config do you mean remove the variant link between linear chassis and secondary linear chassis

**Comment by Yarden-zamir** [comment]
Yes
