### ISSUE TITLE
Would be nice if target blocks were under logic devices

### ISSUE THREAD

**Issue by gamma-delta** [Yarden-zamir/Create-Prepare-to-Dye#440]
They're occasionally helpful for redstoning because they're solid blocks that make redstone dust point into them.

**Comment by gamma-delta** [comment]
Also, note blocks, while I'm asking for things.

**Comment by Yarden-zamir** [comment]
Note block are planned for the framed device, maybe target blocks should be too

**Comment by Yarden-zamir** [comment]
Target blocks are now a furnished device
