### ISSUE TITLE
An example/test issue from github that should actually sync to discord

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create-Prepare-to-Dye#458]

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190416451815866468) 
> 🎉

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190416677205200997) 
> <@&1174653276482977833> I know this is not what you signed up for, but please spam this post to try and break the new bot

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190416790275235850) 
> This is what it looks like on the github side

**Comment by Yarden-zamir** [comment]
This is what it looks like when it comes from github

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190419570180227112) 
> the github page should just be for high priority things like merges pushes reviews n whatnot

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190419609501843570) 
> oh!

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190419628724322365) 
> it's going through now

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190419658684239892) 
> hi github :D

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190419663876784219) 
> a nice

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/270622806520102913/0da3b351a8f687322766906d7ae874ff.webp" width="15" height="15" center=true/> **stinky_toby** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190419692691664978) 
> 👋👋👋

**Comment by Toby222** [comment]
🥛

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190419749352509560) 
> wierd ghost png does NOT embed

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190419787759759490) 
> oh

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/401254336136478732/32f2db537b37df8a123494331b0de45e.webp" width="15" height="15" center=true/> **autistic.sack.of.friends** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190419817296044212) 
> now git2dic is broken...

**Comment by Yarden-zamir** [comment]
1

**Comment by Yarden-zamir** [comment]
hello

**Comment by Yarden-zamir** [comment]
🍅

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190616926548922378) 
> d

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190617186356691045) 
> Alright well it seems that the propper way to do this is using pinned messages, less ideal I think but it works. I also added support for [Discord GitHub Bridge](https://discord.com/channels/890222432605057044/1190415544587931689/1190617186356691045) mentions and [Quark Backpack and inventory tabs](https://discord.com/channels/890222432605057044/1190299014705455115) channel links

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190617249401278516) 
>

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190618135447998525) 
> Can also add image support I think

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190618339643490414) 
> 
https://cdn.discordapp.com/attachments/1190415544587931689/1190618339471540224/Screen_Recording_2023-12-29_at_1.20.05.mov?ex=65a274bc&is=658fffbc&hm=9a84ae0457efbd5953803373f4036d4918f10bcc9cd64c929b94db712f14591f&

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190618421445001216) 
> Yup, this works. Cool. Now formating

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190618556036042803) 
> ![Screen_Shot_2023-12-28_at_12.45.37.png](https://cdn.discordapp.com/attachments/1190415544587931689/1190618556161859724/Screen_Shot_2023-12-28_at_12.45.37.png?ex=65a274f0&is=658ffff0&hm=5f241fe448435926a82cd908292a2eb70e0e5b8f221d3a02f0bf27e795b5982c&)

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190618592648122420) 
> Awesome

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190618665163440208) 
> Now for the github to discords side then

**Comment by Yarden-zamir** [comment]
My favorite thing to do is revert a revert

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1190619312076111923) 
> Cool, shutting this off now while i'm off, I think it's pretty much ready though. Just need to tell the github to discord side not to pin every message

**Comment by Yarden-zamir** [comment]
d

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1192182626795131000) 
> p

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/270622806520102913/0da3b351a8f687322766906d7ae874ff.webp" width="15" height="15" center=true/> **stinky_toby** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1192183010779476100) 
> poop

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1192187314718396487) 
> Reactions do not forward unfortunately

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/162262914898722817/b183775fb56dab06743d29fe1087f6b1.webp" width="15" height="15" center=true/> **engineersmith_4628** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1192188107685101689) 
> thats fine

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/270622806520102913/0da3b351a8f687322766906d7ae874ff.webp" width="15" height="15" center=true/> **stinky_toby** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1192209036519690240) 
> No it's not
I demand them!!! /s

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1192210005311639612) 
> The issue with them is that we only have one bot user

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/b2d749c0f9159013a07a929cffd19285.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1192237346482036878) 
> Should probably also make sure that closing in one place closes in the other

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/270622806520102913/0da3b351a8f687322766906d7ae874ff.webp" width="15" height="15" center=true/> **stinky_toby** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1192416742237012118) 
> True

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1196382095136792666) 
> todo

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1196382276515282954) 
> support for closing issue sync
support for pr sync somehow

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1196382502256918538) 
> ideally messages on prs to appear in realated issues, but then do we sync it to the github issue as well?

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1196389156281139220) 
> also fix email formatting to avoid https://discord.com/channels/890222432605057044/1194946311577935936

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1196396485416321075) 
> also add support for multiple channels so we can add support to github issue sync

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/373597793954299904/db6ea3f492f053c123a6ec4f3d430f15.webp" width="15" height="15" center=true/> **coolandonrs** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1196413012177850378) 
> As I saw when doing [Feature request: Make it free to rename things in the anvil](https://discord.com/channels/890222432605057044/1193510842638024865) I noticed linking an issue to a PR doesn't carry over which should plausibly be done if its not terribly hard

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1196415576067813397) 
> The issue is that I'm not sure what a link means. Does it mean we sync the issue comments to the pr comments and vice versa?

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1196415824093782116) 
> Direct link is already supported as prs are issues behind the scenes but turning it on means that discord will be the source of truth and the pr and issue will have partial info

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/373597793954299904/db6ea3f492f053c123a6ec4f3d430f15.webp" width="15" height="15" center=true/> **coolandonrs** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1196641814569037956) 
> No, I honestly think that all that would be needed is a message saying a PR or Issue was linked to it. That’s all it does in github as well, and I think that’s mostly all that’s needed. PRs should probably stay exclusively on GitHub, and issues on both

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/373597793954299904/db6ea3f492f053c123a6ec4f3d430f15.webp" width="15" height="15" center=true/> **coolandonrs** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1196719969145212948) 
> That’s fair, but I don’t think the comments should carry over PR comments for the most part don’t need to be on discord I think

**Comment by Discord-Github-Bridge** [comment]
[<img src="https://cdn.discordapp.com/avatars/127395969997209600/ed6d18deecd1592788b9747ed256e3b0.webp" width="15" height="15" center=true/> **yarden.zamir** on Discord says](https://discord.com/channels/890222432605057044/1190415544587931689/1196720230630690937) 
> maybe just seperate deve posts for prs is the best aproach
