### ISSUE TITLE
White Ingot not craftable as instructed

### ISSUE THREAD

**Issue by KatrinkaRose** [Yarden-zamir/Create-Prepare-to-Dye#459]
The early advancements instruct the player to press the Raw White into an ingot and then press that into sheets but the raw white presses directly to sheets.

Doesn't seem to functionally be any need for the ingot so this is easy to play past but the advancements should be corrected if this is working as intended.

**Comment by Toby222** [comment]
White ingot has been replaced with sheets. This is indeed a mistake in the advancements.

**Comment by Yarden-zamir** [comment]
Yup. We missed thst when removing ingots. Fixed now

**Comment by chipsams** [comment]
wait, shouldn't this be closed now?
