### ISSUE TITLE
Diesel bug

### ISSUE THREAD

**Issue by EngineerSmith** [Yarden-zamir/Create-Prepare-to-Dye#478]
https://github.com/Yarden-zamir/Create-Prepare-to-Dye/blob/f18e90d0215f938ead28b24b24ec53984f8593c7/kubejs/data/createdieselgenerators/diesel_engine_fuel_types/diesel.json#L2

this line in `diesel.json` shouldn't be `biodiesel`

**Comment by Yarden-zamir** [comment]
woops
