### ISSUE TITLE
add more recipes for shulker shell

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create-Prepare-to-Dye#5]
https://github.com/PandaBoy444/Create.run/blob/9f578bb367b7f7d7cf1e092f19044d2d4484ec0c/Client/scripts/crafting.zs#L1-L16

**Comment by PandaBoy444** [comment]
Maybe instead, we change the shulker box recipe to use tag "shell" or something like that and add that to things like membrane #24

**Comment by Yarden-zamir** [comment]
removed shulker shell instead
