### ISSUE TITLE
 emeralds

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create-Prepare-to-Dye#79]
#77 #78

**Comment by PandaBoy444** [comment]
I want emeralds to be an important resource.
- [ ]  they do not generate in-world
- [ ] they are hard to automate
- [ ] > villagers give you less
> - [ ] j

**Comment by PandaBoy444** [comment]
It would be interesting if you need a lot of emeralds and so breed villigers and automate their trades or make complex processing lines
