### ISSUE TITLE
Stone type making

### ISSUE THREAD

**Issue by Yarden-zamir** [Yarden-zamir/Create-Prepare-to-Dye#88]
andesite, driorite and lime (tho lime might just be limesand, then it's not really a stone

**Comment by PandaBoy444** [comment]
- [ ] andesite
- [ ] driorite
- [ ] lime

**Comment by PandaBoy444** [comment]
By products from ore processing

**Comment by PandaBoy444** [comment]
Remove diorite a d granite from the chain and remove/keep them as decorative only

**Comment by PandaBoy444** [comment]
Andesite will stay as worldgen

**Comment by PandaBoy444** [comment]
Lime will be renamed sandlime and thus processed from sand
